//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwVideoUp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwVideoUp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutThis {
            get {
                return ResourceManager.GetString("AboutThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BitRate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string columnBitrate {
            get {
                return ResourceManager.GetString("columnBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string columnUrl {
            get {
                return ResourceManager.GetString("columnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must less than 15MB :( に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSizeTooLarge {
            get {
                return ResourceManager.GetString("FileSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filesize is too Large! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsFileSizeTooLarge {
            get {
                return ResourceManager.GetString("InsFileSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media Duration is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsMediaTooLong {
            get {
                return ResourceManager.GetString("InsMediaTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must less than 30 sec :( に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaTooLong {
            get {
                return ResourceManager.GetString("MediaTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check URL After Send Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuCheck {
            get {
                return ResourceManager.GetString("menuCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Login (Change Account) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuReauth {
            get {
                return ResourceManager.GetString("menuReauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExit {
            get {
                return ResourceManager.GetString("MsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication is not completed. Do you want to retry? (And exit by clicking on the No) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgUnAuth {
            get {
                return ResourceManager.GetString("MsgUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select file to upload! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleAuth {
            get {
                return ResourceManager.GetString("TitleAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UiButtonAuth {
            get {
                return ResourceManager.GetString("UiButtonAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UiButtonSelect {
            get {
                return ResourceManager.GetString("UiButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Log in to Twitter with following URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UiTextAuthNav {
            get {
                return ResourceManager.GetString("UiTextAuthNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter your PIN below. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UiTextPinNav {
            get {
                return ResourceManager.GetString("UiTextPinNav", resourceCulture);
            }
        }
    }
}
